with-expecter: true
mockname: "{{.InterfaceName}}"
filename: "{{.MockName}}.go"
outpkg: mocks
dir: internal/mocks
packages:
  github.com/eclipse/paho.mqtt.golang:
    interfaces:
      Client:
      Token:
