name: PR Check
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [main]
  workflow_dispatch:

env:
  TEST_TAG: brchri/tesla-youq:test

jobs:
  test-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.x'
      
      - name: Run Go tests
        run: go test ./...

  test-docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and export to docker
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: ${{ env.TEST_TAG }}

      - name: Test
        run: |
          docker run --rm ${{ env.TEST_TAG }} /app/tesla-youq -v
