name: Publish Docker Image

on:
  workflow_dispatch:
    inputs:
      tagVersion:
        type: string
        description: 'Docker image tag to push'
        required: true
      tagLatest:
        type: boolean
        description: 'Add latest tag to image'
        required: true
        default: false
  push:
    tags:
      - 'release-v*'

env:
  REGISTRY_IMAGE: brchri/tesla-youq

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm/v7
          - linux/arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ matrix.platform }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version from git tag
        shell: bash
        if: github.event_name == 'push'
        run: |
          echo "BUILD_VERSION=${GITHUB_REF#refs/tags/release-v}" >> $GITHUB_ENV
          echo "TAG_LATEST=true" >> $GITHUB_ENV
      
      - name: Set version from workflow dispatch
        shell: bash
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "BUILD_VERSION=${{ github.event.inputs.tagVersion }}" >> $GITHUB_ENV
          echo "TAG_LATEST=${{ github.event.inputs.tagLatest }}" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          flavor: latest=${{ env.TAG_LATEST }}
          tags: |
            type=raw,value=${{ env.BUILD_VERSION }}

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.output.labels }}
          tags: ${{ steps.meta.output.tags }}
          build-args: BUILD_VERSION=${{ env.BUILD_VERSION }}
          outputs: type=image,name=${{ env.REGISTRY_IMAGE }},push-by-digest=true,name-canonical=true,push=true
