name: Publish Docker Image

on:
  workflow_dispatch:
    inputs:
      tagVersion:
        type: string
        description: 'Docker image tag to push'
        required: true
      tagLatest:
        type: boolean
        description: 'Add latest tag to image'
        required: true
        default: false
  push:
    tags:
      - 'release-v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image and repo names
        shell: bash
        run: echo "IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/tesla-youq" >> $GITHUB_ENV

      - name: Extract version from git tag
        shell: bash
        if: github.event_name == 'push'
        run: |
          echo "BUILD_VERSION=${GITHUB_REF#refs/tags/release-v}" >> $GITHUB_ENV
          echo "TAG_LATEST=true" >> $GITHUB_ENV
      
      - name: Set version from workflow dispatch
        shell: bash
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "BUILD_VERSION=${{ github.event.inputs.tagVersion }}" >> $GITHUB_ENV
          echo "TAG_LATEST=${{ github.event.inputs.tagLatest }}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          build-args: BUILD_VERSION=${{ env.BUILD_VERSION }}
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.BUILD_VERSION }}
            ${{ env.TAG_LATEST == 'true' && env.IMAGE_NAME+':latest' || '' }}
