name: Publish Docker Image

on:
  push:
    tags:
      - 'release-v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version from Git tag
        id: extract-version
        run: echo "BUILD_VERSION=${GITHUB_REF#refs/tags/release-v}" >> "$GITHUB_OUTPUT"

      - name: Build and Push Docker image
        run: |
          BUILD_VERSION="${{ steps.extract-version.outputs.BUILD_VERSION }}"
          DOCKER_BUILDKIT=1 docker build --build-arg BUILD_VERSION=${BUILD_VERSION} -t ${{ secrets.DOCKERHUB_USERNAME }}/myq-teslamate-geofence:${BUILD_VERSION} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/myq-teslamate-geofence:${BUILD_VERSION}
